# Generated by Django 4.0.6 on 2022-07-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigpotapp', '0005_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='title',
        ),
    ]
