# Generated by Django 4.0.6 on 2022-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpotapp', '0006_remove_freepost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='answer_list',
            field=models.TextField(default='', null=True),
        ),
    ]
