# Generated by Django 4.0.6 on 2022-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigpotapp', '0007_freepost_answer_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freepost',
            old_name='answer_list',
            new_name='food',
        ),
        migrations.AddField(
            model_name='freepost',
            name='time',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='body',
            field=models.TextField(default='', null=True),
        ),
    ]
